@host = http://localhost:8080/api/v1




###
# get host valid in the api
GET {{host}}/scraper/host

### service with can scrap in many servers
POST {{host}}/scraper?page=1&max=50
Content-Type: application/json
{
    "location": "",
    "level": "any",
    "skills": [
        "React-native"
    ],
    "modalities": "remote",
    "minimumSalaryExpectation": -1,
    "maximumSalaryExpectation": -1,
    "category": -1,
    "host": [
        1,
        0
    ]
}

### Send max param
POST {{host}}/scraper/remoteok?max=50
Content-Type: application/json
{
    "location": "",
    "level": "any",
    "skills": [],
    "modalities": "remote",
    "minimumSalaryExpectation": -1,
    "maximumSalaryExpectation": -1,
    "category": 1
}   


###
POST {{host}}/scraper/workremotely
Content-Type: application/json

{
  "location": "",
  "level": "",
  "skills": [],
  "modalities": "",
  "MinimumSalaryExpectation": 5000,
  "maximumSalaryExpectation": 30000,
  "category": -1
}

HTTP/1.1 200  - OK
content-type: application/json
vary: Origin
date: Sun, 13 Jul 2025 04:21:15 GMT
content-length: 66
connection: close

